services:
  todo-db:
    image: postgres:14
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
  nats:
    image: nats
    ports:
      - 4222:4222
    command:
      - "-js"
      - "-v"
